# Generated by Django 4.1.5 on 2023-01-24 16:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=50)),
                ('lastName', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=350, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('genre', models.CharField(max_length=50, null=True)),
                ('synopsis', models.CharField(max_length=350, null=True)),
                ('averageRating', models.DecimalField(decimal_places=1, default=None, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='GRApp.author')),
            ],
        ),
        migrations.CreateModel(
            name='MyBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('WANT', 'Want to read'), ('CURRENTLY', 'Currently reading'), ('ALREADY', 'Already read'), ('DNF', 'Did not finish')], max_length=10)),
                ('note', models.CharField(max_length=350, null=True)),
                ('dateRead', models.DateField()),
                ('owned', models.BooleanField(default=False)),
                ('rating', models.DecimalField(decimal_places=1, default=None, max_digits=2, null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(1)])),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='GRApp.book')),
            ],
        ),
    ]
