# Generated by Django 4.1.5 on 2023-01-28 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GRApp', '0002_alter_mybook_book_myread'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyBook',
        ),
    ]
