# Generated by Django 4.1.5 on 2023-02-06 15:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('GRApp', '0002_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='myread',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='myreads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='myread',
            name='dateRead',
            field=models.DateField(null=True),
        ),
    ]
