# Generated by Django 4.1.5 on 2023-01-30 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRApp', '0003_delete_mybook'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='photo',
            field=models.ImageField(blank=True, default='uploads/default.jpg', upload_to='uploads'),
        ),
    ]
