# Generated by Django 4.1.5 on 2023-02-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRApp', '0004_alter_myread_dateread_alter_myread_note_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myread',
            name='status',
            field=models.CharField(choices=[('Want to read', 'Want to read'), ('Currently reading', 'Currently reading'), ('Already read', 'Already read'), ('Did not finish', 'Did not finish')], max_length=50),
        ),
    ]
