# Generated by Django 4.1.5 on 2023-01-30 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GRApp', '0004_book_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='photo',
            new_name='image',
        ),
    ]
