# Generated by Django 4.1.5 on 2023-01-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRApp', '0005_rename_photo_book_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='image',
            field=models.ImageField(blank=True, default='uploads/default-book.jpg', upload_to='uploads'),
        ),
    ]
