# Generated by Django 4.1.5 on 2023-01-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GRApp', '0006_alter_book_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, default='uploads/default-author.jpg', upload_to='uploads'),
        ),
    ]
